import type { NextPage, GetServerSideProps } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { buscarTodosPosts, Dado, Post } from '../lib/api'
import styles from '../styles/Home.module.css'

interface Props {
    posts: Dado<Post>[],
}

const Home: NextPage<Props> = ({ posts }) => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <ul>
                    {posts.map(post => (
                        <li key={post.id}>{post.attributes.titulo}</li>
                    ))}
                </ul>
            </main>
        </div>
    )
}

export const getServerSideProps: GetServerSideProps<Props> = async () => {
    const resposta = await buscarTodosPosts();
    const posts = resposta.data;

    return {
        props: {
            posts,
        },
    };
};

export default Home
