import type { NextPage, GetServerSideProps } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { buscarTodosPosts, Dado, Post } from '../lib/api'
import styles from '../styles/Home.module.css'

interface Props {
    posts: Dado<Post>[],
    erro?: string,
}

const Home: NextPage<Props> = ({ posts, erro }) => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            
            <main className={styles.main}>
                {/* Mostrar mensagem de erro */}
                {(erro) && (
                    <h1>Tivemos um erro: {erro}</h1>
                )}

                <ul>
                    {posts.map(post => (
                        <li key={post.id}>{post.attributes.titulo}</li>
                    ))}
                </ul>
            </main>
        </div>
    )
}

export const getServerSideProps: GetServerSideProps<Props> = async () => {
    try {
        const resposta = await buscarTodosPosts();
        const posts = resposta.data;

        return {
            props: {
                posts,
            },
        };
    } catch(err: any) {
        return {
            props: {
                posts: [],
                erro: err.toString(),
            }
        }
    }
};

export default Home;
