import type { NextPage, GetServerSideProps } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import { Grid, Button, Card, CardMedia, CardContent, CardActions, Typography } from '@mui/material'
import { buscarTodosPosts, Dado, getMediaURL, Post } from '../lib/api'
import styles from '../styles/Home.module.css'

interface Props {
    posts: Dado<Post>[],
    erro?: string,
}

const capaPadrao = 'https://i.imgur.com/SjKNdU4.jpg';

const Home: NextPage<Props> = ({ posts, erro }) => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Blog</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            
            <main className={styles.main}>
                {/* Mostrar mensagem de erro */}
                {(erro) && (
                    <h1>Tivemos um erro: {erro}</h1>
                )}

                <Grid container justifyContent="center" spacing={3}>
                    {posts.map((post) => (
                        <Grid item key={post.id}>
                            <Card sx={{ minWidth: 300, maxWidth: 300 }}>
                                <CardMedia
                                    component="img"
                                    height="160"
                                    image={capaPadrao}
                                />

                                <CardContent>
                                    <Link href={`/posts/${post.id}`}>
                                        <Typography variant="h5">
                                            {post.attributes.titulo}
                                        </Typography>
                                    </Link>
                                </CardContent>

                                <CardActions>
                                    <Link href={`/posts/${post.id}`}>
                                        <Button>Ler mais</Button>
                                    </Link>
                                </CardActions>
                            </Card>
                        </Grid>
                    ))}
                </Grid>
            </main>
        </div>
    )
}

export const getServerSideProps: GetServerSideProps<Props> = async () => {
    try {
        const resposta = await buscarTodosPosts();
        const posts = resposta.data ?? [];

        return {
            props: {
                posts,
            },
        };
    } catch(err: any) {
        return {
            props: {
                posts: [],
                erro: err.toString(),
            }
        }
    }
};

export default Home;
